/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.BLCatalogos;
import BusinessLogic.BLFuncionalidad;
import BusinessLogic.BLModFuncionalidad;
import BusinessLogic.BLModulo;
import BusinessLogic.BLRol;
import Clases.Funcionalidad;
import Clases.ItemCatalogo;
import Clases.ModFuncionalidad;
import Clases.Modulo;
import Clases.Usuario;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daguaman
 */
public class IFGestionFuncionalidades extends javax.swing.JInternalFrame {
    
    BusinessLogic.BLFuncionalidad objManejadorFuncionalidad = new BLFuncionalidad();
    BusinessLogic.BLCatalogos objManejadorCatalogo = new BLCatalogos();
    BusinessLogic.BLModulo objManejadorModulo = new BLModulo();
    
    BusinessLogic.BLModFuncionalidad objManejadorModFun = new BLModFuncionalidad();
    String IdFuncionalidad = null;
    String FuncionalidadCodigo = null;
    String FuncionalidadNombre = null;
    Modulo modulo = null;

    /**
     * Creates new form IFGestionFuncionalidades
     */
    public IFGestionFuncionalidades() throws SQLException {
        initComponents();
        CargarCatalogo();
        CargarModulos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFunCodigo = new javax.swing.JTextField();
        txtFunNombre = new javax.swing.JTextField();
        cmbFunEstado = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionalidad = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCargar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombreFuncionalidad = new javax.swing.JTextField();
        btnBuscarxNombre = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BtnGuardaModuloFun = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaMods = new javax.swing.JList();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabModFun = new javax.swing.JTable();
        btnDeleteFM = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setTitle("Gestión de Funcionalidades");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestión de Funcionalidades");

        jLabel3.setText("Funcionalidad Codigo");

        jLabel4.setText("Funcionalidad Nombre");

        jLabel5.setText("Funcionalidad Estado");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jTableFuncionalidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFuncionalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionalidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionalidad);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lista de Funcionalidades");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCargar.setText("Cargar Todos");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        jLabel7.setText("Buscar por Nombre de Funcionalidad");

        btnBuscarxNombre.setText("Buscar por Nombre");
        btnBuscarxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarxNombreActionPerformed(evt);
            }
        });

        jLabel8.setText("Modulo al que pertenece");

        BtnGuardaModuloFun.setText("Guardar");
        BtnGuardaModuloFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardaModuloFunActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Asignar una funcionalidad a modulo");

        listaMods.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaMods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaModsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaMods);

        jSeparator1.setBackground(new java.awt.Color(102, 102, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Lista de funcionalidades y Modulos");

        tabModFun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabModFun);

        btnDeleteFM.setText("Eliminar");
        btnDeleteFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFMActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnBuscarxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtNombreFuncionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbFunEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFunNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFunCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnGuardar)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCancelar)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(105, 105, 105)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(BtnGuardaModuloFun, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDeleteFM, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 65, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtFunCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFunNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbFunEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar))))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreFuncionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarxNombre)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteFM, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnGuardaModuloFun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtFunCodigo.getText()!=""&&txtFunNombre.getText()!=""&&cmbFunEstado.getSelectedIndex()!=-1){
            if (GuardarFuncionalidad()==true){
                try {
                    JOptionPane.showMessageDialog(this, "Datos almacenados con exito");
                    RecuperaDatos("-1");
                    Limpiar();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(IFGestionFuncionalidades.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(IFGestionFuncionalidades.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(IFGestionFuncionalidades.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Error al guardar los datos");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe ingresar todos los datos que son obligatorios");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
        try{
            RecuperaDatos("-1");
        }
        catch(Exception ex){
            String msn = ex.getMessage();
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnBuscarxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarxNombreActionPerformed
        try{
            RecuperaDatos(txtNombreFuncionalidad.getText());
        }
        catch(Exception ex){
            String msn = ex.getMessage();
        }
    }//GEN-LAST:event_btnBuscarxNombreActionPerformed

    private void jTableFuncionalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionalidadMouseClicked
        //Recupera la seleccion de filas y Columnas
        int row = (int) jTableFuncionalidad.getSelectedRow();
        IdFuncionalidad = (String) jTableFuncionalidad.getModel().getValueAt(row, 0);
        FuncionalidadCodigo = (String) jTableFuncionalidad.getModel().getValueAt(row, 1);
        FuncionalidadNombre = (String) jTableFuncionalidad.getModel().getValueAt(row, 2);
        String estado = (String)jTableFuncionalidad.getModel().getValueAt(row, 3);
        this.txtFunCodigo.setText(FuncionalidadCodigo);
        this.txtFunNombre.setText(FuncionalidadNombre);
        int est = Integer.parseInt(estado);
        this.cmbFunEstado.setSelectedIndex(est);
        //habilita si llega a existir un Id.
        BtnGuardaModuloFun.setEnabled(true);
    }//GEN-LAST:event_jTableFuncionalidadMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try{
            String mensaje = "Codigo "+ FuncionalidadCodigo + "y nombre " + FuncionalidadNombre;
            int input = JOptionPane.showConfirmDialog(this, "Está seguro que desea eliminar la funcionalidad con " + mensaje);
            // 0 = ok
            // 1 = no
            if (input==0){
                objManejadorFuncionalidad.Eliminar(Integer.parseInt(IdFuncionalidad));
                JOptionPane.showMessageDialog(this, "Datos eliminados con exito");
                RecuperaDatos("-1");
                Limpiar();
            }
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    //falta el id
    int id = Integer.parseInt(IdFuncionalidad);
        if (Actualizar(id)) {
            System.out.println("Editado correctamente");
        try {
            RecuperaDatos("-1");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IFGestionFuncionalidades.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(IFGestionFuncionalidades.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(IFGestionFuncionalidades.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void BtnGuardaModuloFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardaModuloFunActionPerformed
        // TODO add your handling code here:
        //IdFuncionalidad
       int[] intModulos =listaMods.getSelectedIndices();
        int IdeFuncionalidad = Integer.parseInt(IdFuncionalidad);
        if (intModulos.length>0) {
            int idmodulo = modulo.getIdModulo();
            System.out.println("Seleccionado"+idmodulo+IdeFuncionalidad);
           //objManejadorModFun.RegistrarModFuncionalidad(idmodulo,IdeFuncionalidad);
       if (objManejadorModFun.RegistrarModFuncionalidad(idmodulo,IdeFuncionalidad)) {
            System.out.println("Registrado con exito"); 
        }
        else
        {System.out.println("error al regitrar");}
        }
//        if (objManejadorModFun.RegistrarModFuncionalidad(intModulos,IdeFuncionalidad)) {
//            System.out.println("Registrado con exito"); 
//        }
//        else
//        {System.out.println("error al regitrar");}
 
    }//GEN-LAST:event_BtnGuardaModuloFunActionPerformed

    private void listaModsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaModsMouseClicked

        //indice seleccionado
       int[] selectedIx = this.listaMods.getSelectedIndices();
        for (int i = 0; i < selectedIx.length; i++) {
            modulo=(Modulo) listaMods.getModel().getElementAt(selectedIx[i]);
            System.out.println(modulo.getIdModulo());
        }
        
    }//GEN-LAST:event_listaModsMouseClicked

    private void btnDeleteFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFMActionPerformed
        // recupera la seleccion de filas y columnas
        int row =(int) this.tabModFun.getSelectedRow();
        //obtiene el valor de la seleccion
       String idModulo = (String) tabModFun.getModel().getValueAt(row, 0);
       String idFuncion = (String) tabModFun.getModel().getValueAt(row, 1);
      boolean res=  objManejadorModFun.DesasignarModFuncion(Integer.parseInt(idModulo), Integer.parseInt(idFuncion));
        if (res) {
           JOptionPane.showMessageDialog(this, "Modulo/Funcion Desasignado con exito");
            try { 
                ListarModuloFuncion();
            } catch (SQLException ex) {
                Logger.getLogger(IFGestionFuncionalidades.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Error al desasignar modulo/funcion");
        }
    }//GEN-LAST:event_btnDeleteFMActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        try {
            ListarModuloFuncion();
        } catch (SQLException ex) {
            Logger.getLogger(IFGestionFuncionalidades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed
    public void ListarModuloFuncion() throws SQLException{
    try {
    ArrayList<ModFuncionalidad> lstModFun = objManejadorModFun.BuscarModFuncion();
    Object tabla[] =  {"ID_modulo","ID_funcion","Modulo","Funcionalidad"};
    DefaultTableModel modelo = new DefaultTableModel(null,tabla);
    this.tabModFun.setModel(modelo);
    for(ModFuncionalidad objmodfuncional : lstModFun){
    String idModulo = String.valueOf(objmodfuncional.getIdModulo());
    String idFuncion = String.valueOf(objmodfuncional.getIdFuncionalidad());
    String nomMod = String.valueOf(objmodfuncional.getModNombre());
    String nomFun = String.valueOf(objmodfuncional.getFunNombre());
    String modeloTemp[] ={idModulo,idFuncion,nomMod,nomFun};
    modelo.addRow(modeloTemp); 
    }
    this.pack();  
    } catch (SQLException ex) {
            Logger.getLogger(IFRolUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public boolean  Actualizar(int id){
    Funcionalidad objFuncionalidad = new Funcionalidad(id, txtFunCodigo.getText().toUpperCase(), 
                                            txtFunNombre.getText(), 
                                            cmbFunEstado.getSelectedIndex()); 
        return objManejadorFuncionalidad.Actualizar(objFuncionalidad);
    
    }
    public void Limpiar(){
        this.txtFunCodigo.setText(null);
        this.txtFunNombre.setText(null);
        this.cmbFunEstado.setSelectedIndex(0);
    }
    
    public boolean GuardarFuncionalidad(){
        Funcionalidad objFuncionalidad = new Funcionalidad(-1, txtFunCodigo.getText().toUpperCase(), 
                                            txtFunNombre.getText(), 
                                            cmbFunEstado.getSelectedIndex()); 
        return objManejadorFuncionalidad.Registrar(objFuncionalidad);
    }
    public boolean GuardaModuloFuncion(){
    ModFuncionalidad objModFuncion = new ModFuncionalidad();
    
    return true;
    }
    
    public void CargarCatalogo() throws SQLException{
        ArrayList<ItemCatalogo> lstItems = new ArrayList<ItemCatalogo>();
        lstItems =  objManejadorCatalogo.BuscarItemporCatNombre("ESTADO");
        for (int i=0; i<lstItems.size();i++){
            String strNombre = lstItems.get(i).getItcNombre();
            cmbFunEstado.insertItemAt(strNombre, i);
        }
        
    }
      public void CargarModulos() throws SQLException{
        DefaultListModel<Modulo> dlm = new DefaultListModel<>();
          ArrayList<Modulo> lstMods = objManejadorModulo.BuscarMod();
       // lstMods =  
        Modulo objMod=null;
          for (Modulo md : lstMods) {
             objMod = new Modulo(md.getIdModulo(),md.getModNombre(),md.getModEstado()); 
          dlm.addElement(objMod);
          }
        listaMods.setModel(dlm);
    }
    
    public void RecuperaDatos(String strFunNombre) throws ClassNotFoundException, IOException, SQLException{
        ArrayList<Funcionalidad> lstFuncionalidad = objManejadorFuncionalidad.Buscar(strFunNombre);
        Object columnas[] = {"IdFuncionalidad", "Codigo", "Nombre", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTableFuncionalidad.setModel(modelo);
        for (Funcionalidad func : lstFuncionalidad) {
            String id = String.valueOf(func.getIdFuncionalidad());
            String codigo = func.getFunCodigo();
            String nombre = func.getFunNombre();
            String estado = String.valueOf(func.getFunEstado());
            String modeloTemp[] = {id, codigo, nombre, estado};
            modelo.addRow(modeloTemp);
        }
        this.pack();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardaModuloFun;
    private javax.swing.JButton btnBuscarxNombre;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnDeleteFM;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox cmbFunEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableFuncionalidad;
    private javax.swing.JList listaMods;
    private javax.swing.JTable tabModFun;
    private javax.swing.JTextField txtFunCodigo;
    private javax.swing.JTextField txtFunNombre;
    private javax.swing.JTextField txtNombreFuncionalidad;
    // End of variables declaration//GEN-END:variables
}
