/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.BLCatalogos;
import BusinessLogic.BLUsuario;
import Clases.ItemCatalogo;
import Clases.Usuario;

//import ManejaArchivos.OperaUsuario;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daguaman
 */
public class IFGestionUsuarios extends javax.swing.JInternalFrame {
    BusinessLogic.BLCatalogos objManejadorCatalogo = new BLCatalogos();
    BusinessLogic.BLUsuario objManejadorUsuarios = new BLUsuario();
    public String IdUsuario;
   public String Identificacion;
   public String Nombres;
   public String Apellidos;
   public String Login;
   public String Password;
   public String estado, pais, genero;
    /**
     * Creates new form IFGestionUsuarios
     */
//    ManejaArchivos.OperaUsuario objArcUsuario = new OperaUsuario();
    public IFGestionUsuarios() throws SQLException {
        initComponents();
        CargarCatalogo();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSeleccion = new javax.swing.JLabel();
        lblSeleccion2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtIdBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        cmbEstado = new javax.swing.JComboBox();
        cmbPais = new javax.swing.JComboBox();
        cmbGenero = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion de Usuarios");
        setVisible(true);

        btnConsultarTodos.setText("ConsultarTodos");
        btnConsultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTodosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Lista de Usuarios");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Valores Seleccionados");

        lblSeleccion.setText("-");

        lblSeleccion2.setText("-");

        jLabel12.setText("Criterio de Busqueda: Num_Identificacion");

        jButton1.setText("Buscar por Num Identificacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Genero");

        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTIÓN DE USUARIOS");

        jLabel2.setText("Identificacion");

        jLabel3.setText("Nombres");

        jLabel4.setText("Apellidos");

        jLabel5.setText("Login");

        jLabel6.setText("Password");

        jLabel7.setText("Estado");

        jLabel8.setText("Pais");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar Usuario Seleccionado");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar Seleccionado");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdentificacion)
                                    .addComponent(txtNombres)
                                    .addComponent(txtApellidos)
                                    .addComponent(txtLogin)
                                    .addComponent(txtPass)
                                    .addComponent(cmbEstado, 0, 186, Short.MAX_VALUE)
                                    .addComponent(cmbPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdBusqueda, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeleccion2)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(lblSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnConsultarTodos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 10, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarTodos)
                            .addComponent(btnEliminar)
                            .addComponent(btnActualizar))
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeleccion)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSeleccion2)
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTodosActionPerformed
        try {
            RecuperaDatos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnConsultarTodosActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //Recupera la seleccion de filas y Columnas
        int row = (int) jTable1.getSelectedRow();
        int column = (int) jTable1.getSelectedColumn();
        //Obtiene el valor de la seleccion
        String strValor = (String) jTable1.getModel().getValueAt(row, column);
        //Muestra en la eqiqueta
        lblSeleccion.setText(strValor);
        IdUsuario =  (String) jTable1.getModel().getValueAt(row, 0);
        Identificacion = (String) jTable1.getModel().getValueAt(row, 1);
        Nombres = (String) jTable1.getModel().getValueAt(row, 2);
        Apellidos = (String) jTable1.getModel().getValueAt(row, 3);
        Login = (String) jTable1.getModel().getValueAt(row, 4);
        Password = (String) jTable1.getModel().getValueAt(row, 5);
        estado= (String) jTable1.getModel().getValueAt(row, 6);
        pais= (String) jTable1.getModel().getValueAt(row, 7);
        genero= (String) jTable1.getModel().getValueAt(row, 8);
        lblSeleccion2.setText(IdUsuario + " - " + Identificacion + " - " + Nombres + " - " + Apellidos + " - " +
            Login + " - " + Password);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            RecuperaDatosPorCriterio(txtIdBusqueda.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // Para visualizar la obtención de indice y valor asociado al combobox
        System.out.println("Index" + cmbEstado.getSelectedIndex());
        System.out.println("Item" + cmbEstado.getSelectedItem().toString());
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (btnGuardar.getText().equals("Guardar")) {
           boolean resultado = GuardarUsuario();
        if (resultado==true){
                JOptionPane.showMessageDialog(this, "Datos almacenados con exito");
                Limpiar();            
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al guardar los datos");
            }  
        }
        else
        {
        //acccion de actualizar
            if (ActualizarUsuario()) {
                System.out.println("Actualziado exitosamente");                 
            }
            else{
                System.out.println("Error al actualziar");
            }
            this.btnGuardar.setText("Guardar");
            Limpiar();           
        }
        //actualiza de todas maneras
         try {
                RecuperaDatos();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       int id= Integer.parseInt(IdUsuario);
        try {
            if (EliminarUsuario(id)) {
                System.out.println("Eliminado correctamente");
                RecuperaDatos();
            }
            else{
                System.out.println("No se puede eliminar datos inexistentes");
            }
 
        } catch (SQLException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int est=Integer.parseInt(estado),pai=Integer.parseInt(pais),gen=Integer.parseInt(genero);   
        this.txtIdentificacion.setText(Identificacion);
            this.txtNombres.setText(Nombres);
            this.txtApellidos.setText(Apellidos);
            this.txtLogin.setText(Login);
            this.txtPass.setText(Password);
            this.cmbEstado.setSelectedIndex(est);
            this.cmbPais.setSelectedIndex(pai);
            this.cmbGenero.setSelectedIndex(gen);
            this.btnGuardar.setText("actualizar");
        
       /// ActualizarUsuario();  //solo si hay datos cargados     
    }//GEN-LAST:event_btnActualizarActionPerformed

    public void CargarCombos(){
        BusinessLogic.BLCatalogos objManejadorCatalogo = new BLCatalogos();
       
    }
   
    public void CargarCatalogo() throws SQLException{
        ArrayList<ItemCatalogo> lstEstado = new ArrayList<ItemCatalogo>();
        ArrayList<ItemCatalogo> lstPais = new ArrayList<ItemCatalogo>();
        ArrayList<ItemCatalogo> lstGenero = new ArrayList<ItemCatalogo>();
        lstEstado =  objManejadorCatalogo.BuscarItemporCatNombre("ESTADO");
        for (int i=0; i<lstEstado.size();i++){
            int idItem = lstEstado.get(i).getIdItemCatalogo();
            String strNombre = lstEstado.get(i).getItcNombre();
            cmbEstado.insertItemAt(strNombre, i);
        }
        
        lstPais =  objManejadorCatalogo.BuscarItemporCatNombre("PAIS");
        for (int i=0; i<lstPais.size();i++){
            int idItem = lstPais.get(i).getIdItemCatalogo();
            String strNombre = lstPais.get(i).getItcNombre();
            cmbPais.insertItemAt(strNombre, i);
        }
        
        lstGenero =  objManejadorCatalogo.BuscarItemporCatNombre("GENERO");
        for (int i=0; i<lstGenero.size();i++){
            int idItem = lstGenero.get(i).getIdItemCatalogo();
            String strNombre = lstGenero.get(i).getItcNombre();
            cmbGenero.insertItemAt(strNombre, i);
        }        
        
    }
    
    public void Limpiar(){
        this.txtIdentificacion.setText(null);
        this.txtNombres.setText(null);
        this.txtApellidos.setText(null);
        this.txtLogin.setText(null);
        this.txtPass.setText(null);
        cmbEstado.setSelectedIndex(0);
        cmbGenero.setSelectedIndex(0);
        cmbPais.setSelectedIndex(0);
    }
    
    public boolean GuardarUsuario(){
        System.out.println("Enviar a Insertar Usuario en BDD");
        
        Usuario objUsuario = new Usuario(-1, txtIdentificacion.getText(), //enviar en blanco
                                            txtNombres.getText(), 
                                            txtApellidos.getText(), 
                                            txtLogin.getText(), 
                                            txtPass.getText(), 
                                            cmbEstado.getSelectedIndex(), 
                                            cmbPais.getSelectedIndex(), 
                                            cmbGenero.getSelectedIndex());
        return objManejadorUsuarios.Registrar(objUsuario);
        
    }
    
  public boolean ActualizarUsuario(){
       int id= Integer.parseInt(IdUsuario);
        System.out.println("Enviar a actualizar Usuario en BDD");
        Usuario objUsuario = new Usuario(id, txtIdentificacion.getText(), 
                                            txtNombres.getText(), 
                                            txtApellidos.getText(), 
                                            txtLogin.getText(), 
                                            txtPass.getText(), 
                                            cmbEstado.getSelectedIndex(), 
                                            cmbPais.getSelectedIndex(), 
                                            cmbGenero.getSelectedIndex());
                                            
        return objManejadorUsuarios.Modificar(objUsuario);
        
    }  
    public void RecuperaDatos() throws ClassNotFoundException, IOException, SQLException{
        ArrayList<Usuario> lstUsuario = objManejadorUsuarios.Buscar("-1");
        Object columnas[] = {"Id", "Identificacion", "Nombres", "Apellidos", "Login", "Password", "Estado", "Pais", "Genero"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);
        for (Usuario usu : lstUsuario) {
            String id = String.valueOf(usu.getIdUsuario());
            String identificacion = usu.getUsIdentificacion();
            String nombre = usu.getUsNombres();
            String apellido = usu.getUsApellidos();
            String login = usu.getUsLogin();
            String pass = usu.getUsPassword();
            String Estado = String.valueOf(usu.getUsEstado());
            String Pais = String.valueOf(usu.getUsPais());
            String Genero = String.valueOf(usu.getUsGenero());
            String modeloTemp[] = {id, identificacion, nombre, apellido, login, pass, Estado, Pais, Genero};
            modelo.addRow(modeloTemp);
        }
        this.pack();
    }

    public void RecuperaDatosPorCriterio(String strIdentificacion) throws ClassNotFoundException, IOException, SQLException{
     
         ArrayList<Usuario> lstUsuario = objManejadorUsuarios.Buscar(strIdentificacion);
        Object columnas[] = {"Id", "Identificacion", "Nombres", "Apellidos", "Login", "Password", "Estado", "Pais", "Genero"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);
        for (Usuario usu : lstUsuario) {
            String id = String.valueOf(usu.getIdUsuario());
            String identificacion = usu.getUsIdentificacion();
            String nombre = usu.getUsNombres();
            String apellido = usu.getUsApellidos();
            String login = usu.getUsLogin();
            String pass = usu.getUsPassword();
            String Estado = String.valueOf(usu.getUsEstado());
            String Pais = String.valueOf(usu.getUsPais());
            String Genero = String.valueOf(usu.getUsGenero());
            String modeloTemp[] = {id, identificacion, nombre, apellido, login, pass, Estado, Pais, Genero};
            modelo.addRow(modeloTemp);
        }
        this.pack();
        
        
        
        
        
     /*
        //ArrayList<Usuario> lstUsuario = objArcUsuario.RecuperaUsuario();
        Object columnas[] = {"Id", "Identificacion", "Nombres", "Apellidos", "Login", "Password", "Estado", "Pais", "Genero"};
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);
        boolean encontrado = false;
        for (Usuario usu : lstUsuario)
        {
            String identificacion = usu.getUsIdentificacion();
            if (identificacion.trim().equals(strIdentificacion.trim())){
                String id = String.valueOf(usu.getIdUsuario());
                String nombre = usu.getUsNombres();
                String apellido = usu.getUsApellidos();
                String login = usu.getUsLogin();
                String pass = usu.getUsPassword();
                String Estado = String.valueOf(usu.getUsEstado());
                String Pais = String.valueOf(usu.getUsPais());
                String Genero = String.valueOf(usu.getUsGenero());
                String modeloTemp[] = {id, identificacion, nombre, apellido, login, pass, Estado, Pais, Genero};
                modelo.addRow(modeloTemp);
                encontrado = true;
            }
        }
        if (encontrado == false){
            JOptionPane.showMessageDialog(this, "No existen datos asociados a la identificacion" + strIdentificacion);
        }
        this.pack();
*/
    }
   
    public boolean EliminarUsuario(int intIdentificacion) throws SQLException{
    boolean estado = objManejadorUsuarios.Eliminar(intIdentificacion);
      return estado;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultarTodos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbGenero;
    private javax.swing.JComboBox cmbPais;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSeleccion;
    private javax.swing.JLabel lblSeleccion2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtIdBusqueda;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

    private void ConsultarUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
