/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.BLCatalogos;
import Clases.Catalogo;
import Clases.ItemCatalogo;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daguaman
 */
public class IFGestionCatalogos extends javax.swing.JInternalFrame {
  public String  Id;
   public String Codigo;
   public String Nombre;
   public String Descripcion;
   public String Estado;
   public String IdCatalogo;//para eliminar un elemento del itemcatalogo
   public String accion="guardar";
    /**
     * Creates new form IFGestionCatalogos
     */
    BusinessLogic.BLCatalogos objManejadorCatalogos = new BLCatalogos();
    
    public IFGestionCatalogos() {
        initComponents();
        CargarEstadoDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void CargarEstadoDefault(){
        cmbEstado.insertItemAt("Inactivo", 0);
        cmbEstado.insertItemAt("Activo", 1);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtcatDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcatNombre = new javax.swing.JTextField();
        txtcatCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtItcCod = new javax.swing.JTextField();
        txtItcNombre = new javax.swing.JTextField();
        txtItcDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnGuardarCat = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCatalogo = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardarItem = new javax.swing.JButton();
        btnLimpiarItem = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableItemCatalogo = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        delItem = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestión de Catálogos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Catálogos e Items");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Catálogos");

        jLabel5.setText("Descripción");

        jLabel4.setText("Nombre");

        jLabel3.setText("Codigo");

        jLabel10.setText("Estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcatCodigo)
                            .addComponent(txtcatNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcatDescripcion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcatCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcatNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtcatDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel7.setText("Codigo");

        jLabel8.setText("Nombre");

        jLabel9.setText("Descripción");

        txtItcCod.setEnabled(false);

        txtItcNombre.setEnabled(false);

        txtItcDescripcion.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtItcDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtItcCod)
                            .addComponent(txtItcNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtItcCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtItcNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtItcDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Item Catalogo");

        btnGuardarCat.setText("Guardar");
        btnGuardarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCatActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jTableCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCatalogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCatalogo);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Lista de Catálogos");

        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardarItem.setText("Guardar");
        btnGuardarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarItemActionPerformed(evt);
            }
        });

        btnLimpiarItem.setText("Limpiar");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Lista de Item de Catálogos");

        jTableItemCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableItemCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItemCatalogoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableItemCatalogo);

        jButton3.setText("Listar Todos Item Catalogo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton5.setText("Añadir Item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        delItem.setText("Eliminar Item");
        delItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(btnGuardarCat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnGuardarItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarItem)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEditar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEliminar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addGap(18, 18, 18)
                                                .addComponent(delItem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarCat)
                            .addComponent(btnLimpiar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar)
                            .addComponent(jButton5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarItem)
                    .addComponent(btnLimpiarItem)
                    .addComponent(jButton3)
                    .addComponent(delItem))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCatActionPerformed
        try{
            if (accion.equals("guardar")) {
              if (txtcatCodigo.getText()!=null && txtcatNombre.getText()!=null && txtcatDescripcion.getText()!=null){
                String strCatCodigo = txtcatCodigo.getText();
                String strCatNombe = txtcatNombre.getText();
                String strCatDescripcion = txtcatDescripcion.getText();
                int intCatEstado = cmbEstado.getSelectedIndex(); 
                Catalogo objCatalogo = new Catalogo(-1, strCatCodigo, strCatNombe, strCatDescripcion, intCatEstado);
                boolean resultado = GuardarCatalogo(objCatalogo);
                if (resultado==true){
                    JOptionPane.showMessageDialog(this, "Datos almacenados con exito");
                    RecuperaDatos();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error al guardar los datos");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Debe ingresar todos los datos de Catálogo");
            }  
            }
            else{
            //codigo de actualizar 
              int id= Integer.parseInt(Id);
            if (txtcatCodigo.getText()!=null && txtcatNombre.getText()!=null && txtcatDescripcion.getText()!=null){
                String strCatCodigo = txtcatCodigo.getText();
                String strCatNombe = txtcatNombre.getText();
                String strCatDescripcion = txtcatDescripcion.getText();
                int intCatEstado = cmbEstado.getSelectedIndex(); 
                Catalogo objCatalogo = new Catalogo(id, strCatCodigo, strCatNombe, strCatDescripcion, intCatEstado);
                boolean resultado = ActualizarCatalogo(objCatalogo);
                if (resultado==true){
                    JOptionPane.showMessageDialog(this, "Datos almacenados con exito");
                    RecuperaDatos();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error al guardar los datos");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Debe ingresar todos los datos de Catálogo");
            }  
            accion="guardar";
            }
            
        }
        catch(Exception ex){
            String msn = ex.getMessage();
        }
    }//GEN-LAST:event_btnGuardarCatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            RecuperaDatos();
        }
        catch(Exception ex){
            String msn = ex.getMessage();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTableCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCatalogoMouseClicked
        //Recupera la seleccion de filas y Columnas
        int row = (int) jTableCatalogo.getSelectedRow();
        int column = (int) jTableCatalogo.getSelectedColumn();
        //Obtiene el valor de la seleccion
         Id = (String)jTableCatalogo.getModel().getValueAt(row, 0);
         Codigo = (String) jTableCatalogo.getModel().getValueAt(row, 1);
         Nombre = (String) jTableCatalogo.getModel().getValueAt(row, 2);
         Descripcion = (String) jTableCatalogo.getModel().getValueAt(row, 3);
         Estado = (String) jTableCatalogo.getModel().getValueAt(row, 4);
       // txtcatCodigo.setText(Codigo);
       // txtcatNombre.setText(Nombre);
       // txtcatDescripcion.setText(Descripcion);
       // cmbEstado.setSelectedIndex(Integer.parseInt(Estado));
        
        try {
            //Llama al método que permite consultar los items de Catalogo
            ConsultarItemCatalogo(Integer.parseInt(Id));
        } catch (SQLException ex) {
            Logger.getLogger(IFGestionCatalogos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTableCatalogoMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //desbloquea las cajas de texto para agregar un nuevo catalogo
        txtItcCod.setEnabled(true);
        txtItcDescripcion.setEnabled(true);
        txtItcNombre.setEnabled(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtcatCodigo.setText(null);
        txtcatDescripcion.setText(null);
        txtcatNombre.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarItemActionPerformed
        try {
            // TODO add your handling code here:
            GuardarItemCatalogo();
        } catch (SQLException ex) {
            Logger.getLogger(IFGestionCatalogos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGuardarItemActionPerformed

    private void jTableItemCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItemCatalogoMouseClicked
        // TODO add your handling code here:
        //Recupera la seleccion de filas y Columnas
        int row = (int) jTableItemCatalogo.getSelectedRow();
        int column = (int) jTableItemCatalogo.getSelectedColumn();
        //Obtiene el valor de la seleccion
         IdCatalogo = (String)jTableItemCatalogo.getModel().getValueAt(row, 0);
        String Codigo = (String) jTableItemCatalogo.getModel().getValueAt(row, 1);
        String Nombre = (String) jTableItemCatalogo.getModel().getValueAt(row, 2);
        String Descripcion = (String) jTableItemCatalogo.getModel().getValueAt(row, 3);
        txtItcCod.setText(Codigo);
        txtItcNombre.setText(Nombre);
        txtItcDescripcion.setText(Descripcion);
    }//GEN-LAST:event_jTableItemCatalogoMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id= Integer.parseInt(Id);
      try {
          if (EliminarCatalago(id)) {
              System.out.println("Eliminado correctamente");
              RecuperaDatos();
          }
          else{
              System.out.println("No se puede eliminar datos inexistentes");
          }

      } catch (SQLException ex) {
          Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
          Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void delItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delItemActionPerformed
         int idCa= Integer.parseInt(IdCatalogo);
      try {
          if (EliminarItemCatalago(idCa)) {
              System.out.println("Eliminado correctamente");
              RecuperaDatos();
          }
          else{
              System.out.println("No se puede eliminar datos inexistentes");
          }

      } catch (SQLException ex) {
          Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
      } catch (ClassNotFoundException ex) {
          Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
          Logger.getLogger(IFGestionUsuarios.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_delItemActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       accion="actualizar";
        int est=Integer.parseInt(Estado);   
          this.txtcatCodigo.setText(Id);
          this.txtcatNombre.setText(Nombre);
          this.txtcatDescripcion.setText(Descripcion);
          this.cmbEstado.setSelectedIndex(est);
    }//GEN-LAST:event_btnEditarActionPerformed
   
    public boolean EliminarCatalago(int intIdCat) throws SQLException{
     boolean estado = objManejadorCatalogos.EliminarCatalogo(intIdCat);
     return estado;
     }
    public boolean ActualizarCatalogo(Catalogo objCatalogo){
        return objManejadorCatalogos.ModificarCatalogo(objCatalogo);
    }
    public boolean GuardarCatalogo(Catalogo objCatalogo){
        return objManejadorCatalogos.RegistrarCatalogo(objCatalogo);
    }
    public boolean EliminarItemCatalago(int idItemCatalogoo){
      boolean estado = objManejadorCatalogos.EliminarItemCatalogo(idItemCatalogoo);
     return estado;

}
    
    public boolean GuardarItemCatalogo() throws SQLException{

        int row = (int) jTableCatalogo.getSelectedRow();
        int column = (int) jTableCatalogo.getSelectedColumn();
        //Obtiene el valor del Catalogo para asociarlo al Item
        String IdCatalogo = (String) jTableCatalogo.getModel().getValueAt(row, 0);
        ItemCatalogo objItemCatalogo = new ItemCatalogo(-1, txtItcCod.getText(), txtItcNombre.getText(), txtItcDescripcion.getText(), Integer.parseInt(IdCatalogo));
        LimpiarCajasItem();
        ConsultarItemCatalogo(Integer.parseInt(IdCatalogo));
        return objManejadorCatalogos.RegistrarItemCatalogo(Integer.parseInt(IdCatalogo), objItemCatalogo);
        
    }
    
    public void LimpiarCajasItem(){
        txtItcCod.setText("");
        txtItcNombre.setText("");
        txtItcDescripcion.setText("");

    }
    
    public void ConsultarItemCatalogo(int intId) throws SQLException{
    int intExistencia = objManejadorCatalogos.ContarItemCatalogo(intId);
    
        if (intExistencia>0)
        {
            ArrayList<ItemCatalogo> lstItemCatalogo = objManejadorCatalogos.BuscarItemCatalogo(intId);
            /*Es necesario crear un objeto con las columnas que se mostrarán en la tabla*/
                Object columnas[] = {"idItemCatalogo", "itcCodigo", "itcNombre", "itcDescripcion", "idCatalogo"};
                /*Es necesario añadir las columnas al modelo de la Tabla*/
                DefaultTableModel modelo = new DefaultTableModel(null, columnas);
                /*Añadidas las columnas y el modelo se setea en la Tabla*/
                jTableItemCatalogo.setModel(modelo);
                for (ItemCatalogo objICat : lstItemCatalogo) {
                    String id = String.valueOf(objICat.getIdItemCatalogo());
                    String codigo = objICat.getItcCodigo();
                    String nombre = objICat.getItcNombre();
                    String descripcion = objICat.getItcDescripcion();
                    String catId = String.valueOf(objICat.getIdCatalogo());
                    //Por cada registro se lo añade a una estructra tipo Arreglo para incluirlo en la Tabla
                    String modeloTemp[] = {id, codigo, nombre, descripcion, catId};
                    //Se añade la estructura al modelo de la Tabla
                    modelo.addRow(modeloTemp);
                }
                this.pack();
        }
        else{
            Object columnas[] = {"idItemCatalogo", "itcCodigo", "itcNombre", "itcDescripcion", "idCatalogo"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);
            jTableItemCatalogo.setModel(modelo);
            this.pack();
            txtItcCod.setText(null);
            txtItcNombre.setText(null);
            txtItcDescripcion.setText(null);
        }
    }
    
    
    
    
    public void RecuperaDatos() throws ClassNotFoundException, IOException, SQLException{
        ArrayList<Catalogo> lstCatalogo = objManejadorCatalogos.Buscar("-1");
        /*Es necesario crear un objeto con las columnas que se mostrarán en la tabla*/
        Object columnas[] = {"idcatalogo", "catCodigo", "catNombre", "catDescripcion", "catEstado"};
        /*Es necesario añadir las columnas al modelo de la Tabla*/
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        /*Añadidas las columnas y el modelo se setea en la Tabla*/
        jTableCatalogo.setModel(modelo);
        for (Catalogo objCat : lstCatalogo) {
            String id = String.valueOf(objCat.getIdCatalogo());
            String codigo = objCat.getCatCodigo();
            String nombre = objCat.getCatNombre();
            String descripcion = objCat.getCatDescripcion();
            String estado = String.valueOf(objCat.getCatEstado());
            //Por cada registro se lo añade a una estructra tipo Arreglo para incluirlo en la Tabla
            String modeloTemp[] = {id, codigo, nombre, descripcion, estado};
            //Se añade la estructura al modelo de la Tabla
            modelo.addRow(modeloTemp);
        }
        this.pack();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarCat;
    private javax.swing.JButton btnGuardarItem;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarItem;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JButton delItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCatalogo;
    private javax.swing.JTable jTableItemCatalogo;
    private javax.swing.JTextField txtItcCod;
    private javax.swing.JTextField txtItcDescripcion;
    private javax.swing.JTextField txtItcNombre;
    private javax.swing.JTextField txtcatCodigo;
    private javax.swing.JTextField txtcatDescripcion;
    private javax.swing.JTextField txtcatNombre;
    // End of variables declaration//GEN-END:variables
}
