/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.BLCatalogos;
import BusinessLogic.BLModulo;
import Clases.ItemCatalogo;
import Clases.Modulo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daguaman
 */
public class IFGestionModulos extends javax.swing.JInternalFrame {
  BusinessLogic.BLModulo objManejadorMod = new BLModulo();
   BusinessLogic.BLCatalogos objManejadorCatalogo = new BLCatalogos();
    public String idModulo;
    /**
     * Creates new form IFGestionModulos
     */
    public IFGestionModulos() throws SQLException {
        initComponents();
        CargarCatalogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombreMod = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnListarMod = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbEstadoRol = new javax.swing.JComboBox();
        BtnEliminaMod = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Gestión de Módulos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Módulos");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnListarMod.setText("Listar Modulo");
        btnListarMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarModActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Lista de Modulos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        cmbEstadoRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoRolActionPerformed(evt);
            }
        });

        BtnEliminaMod.setText("Eliminar Seleccioando");
        BtnEliminaMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminaModActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Rol");

        jLabel3.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbEstadoRol, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(btnGuardar)
                                        .addGap(14, 14, 14)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnListarMod)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BtnEliminaMod)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(123, 123, 123)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 442, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cmbEstadoRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnListarMod)))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(BtnEliminaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

      String strNombre = txtNombreMod.getText();
       String strEstado = (String)cmbEstadoRol.getSelectedItem();
       Modulo objMod = new Modulo(-1, strNombre, strEstado);
       boolean resultado = Guardar(objMod);
       if (resultado==true){
           JOptionPane.showMessageDialog(this, "Datos almacenados con exito");
           try {
               Consultar();
           } catch (SQLException ex) {
               Logger.getLogger(IFGestionRoles.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else{
           JOptionPane.showMessageDialog(this, "Error al guardar los datos");
       }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListarModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarModActionPerformed
        try {
            // TODO add your handling code here:
            Consultar();
        } catch (SQLException ex) {
            Logger.getLogger(IFGestionRoles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarModActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //Recupera la seleccion de filas y Columnas
        int row = (int) jTable1.getSelectedRow();
        int column = (int) jTable1.getSelectedColumn();
        //Obtiene el valor de la seleccion
        String strValor = (String) jTable1.getModel().getValueAt(row, column);
        //Muestra en la eqiqueta
        idModulo = (String) jTable1.getModel().getValueAt(row, 0);
        String nomRol = (String) jTable1.getModel().getValueAt(row, 1);
        String Estado = (String) jTable1.getModel().getValueAt(row, 2);
        cmbEstadoRol.setSelectedItem(Estado);
        txtNombreMod.setText(nomRol);

    }//GEN-LAST:event_jTable1MouseClicked

    private void cmbEstadoRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoRolActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this,cmbEstadoRol.getSelectedIndex());
        //JOptionPane.showMessageDialog(this,cmbEstadoRol.getSelectedItem());
    }//GEN-LAST:event_cmbEstadoRolActionPerformed

    private void BtnEliminaModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminaModActionPerformed
        int id = Integer.parseInt(idModulo);
        System.out.println(id);
        if (Eliminar(id)) {
            try {
                Consultar();
            } catch (SQLException ex) {
                Logger.getLogger(IFGestionRoles.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_BtnEliminaModActionPerformed
  public boolean Guardar(Modulo objMod){
       return objManejadorMod.Registrar(objMod);
   }
  public void Consultar() throws SQLException{
       ArrayList<Modulo> lstMod = objManejadorMod.BuscarMod();
       /*Es necesario crear un objeto con las columnas que se mostrarán en la tabla*/
       Object columnas[] = {"idModulo", "modNombre", "modEstado"};
       /*Es necesario añadir las columnas al modelo de la Tabla*/
       DefaultTableModel modelo = new DefaultTableModel(null, columnas);
       /*Añadidas las columnas y el modelo se setea en la Tabla*/
       jTable1.setModel(modelo);
       for (Modulo objMod : lstMod) {
           String idModulo = String.valueOf(objMod.getIdModulo());
           String modNombre = objMod.getModNombre();
           String modEstado = objMod.getModEstado();
           String modeloTemp[] = {idModulo, modNombre, modEstado};
           modelo.addRow(modeloTemp);
       }
       this.pack();
   }
  private boolean Eliminar(int id) {
        boolean estado = objManejadorMod.Eliminar(id);
    return estado;
   }
   public void CargarCatalogo() throws SQLException{
       ArrayList<ItemCatalogo> lstItems = new ArrayList<ItemCatalogo>();
       lstItems =  objManejadorCatalogo.BuscarItemporCatNombre("ESTADO");
       for (int i=0; i<lstItems.size();i++){
           int idItem = lstItems.get(i).getIdItemCatalogo();
           String strNombre = lstItems.get(i).getItcNombre();
           cmbEstadoRol.insertItemAt(strNombre, i);
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminaMod;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListarMod;
    private javax.swing.JComboBox cmbEstadoRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNombreMod;
    // End of variables declaration//GEN-END:variables
}
