/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.BLFuncionalidad;
import BusinessLogic.BLRol;
import BusinessLogic.BLRolFuncionalidad;
import Clases.Funcionalidad;
import Clases.Rol;
import Clases.RolFuncionalidad;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daguaman
 */
public class IFGestionRolFuncionalidad extends javax.swing.JInternalFrame {
    BusinessLogic.BLRol objManejadorRoles = new BLRol();
    BusinessLogic.BLFuncionalidad  objManejadorFuncionalidad = new BLFuncionalidad();
    BusinessLogic.BLRolFuncionalidad objManejadorRolFuncionalidad = new BLRolFuncionalidad();
    Rol rol =null;
    Funcionalidad func =null;
    
    

    /**
     * Creates new form IFGestionRolFuncionalidad
     */
    public IFGestionRolFuncionalidad() throws SQLException {
        initComponents();
        CargarRoles();
        CargarFuncionalidades();
        ListarRolFuncionalidad();

    }
    
    public void CargarRoles() throws SQLException{
        DefaultListModel<Rol> dlm = new DefaultListModel<>();
        ArrayList<Rol> lstRol = objManejadorRoles.BuscarRol();
        Rol objRol = null;
        for (Rol lstRol1 : lstRol) {
            objRol = new Rol(lstRol1.getIdRol(), lstRol1.getRolNombre());
            dlm.addElement(objRol);
        }
        listaRol.setModel(dlm);
    }
    
    public void CargarFuncionalidades() throws SQLException{
        DefaultListModel<Funcionalidad> dlm = new DefaultListModel<>();
        ArrayList<Funcionalidad> lstFuncionalidad = objManejadorFuncionalidad.Buscar("-1");
        Funcionalidad objFuncionalidad = null;
        for (Funcionalidad lstFuncionalidad1 : lstFuncionalidad) {
            objFuncionalidad = new Funcionalidad(lstFuncionalidad1.getIdFuncionalidad(), lstFuncionalidad1.getFunNombre());
            dlm.addElement(objFuncionalidad);
        }
        listaFuncionalidad.setModel(dlm);
    }
    
    public void ListarRolFuncionalidad(){
    try {
        ArrayList<RolFuncionalidad> lstRolFuncionalidad =  objManejadorRolFuncionalidad.BuscarRolFuncionalidad();
        /*Es necesario crear un objeto con las columnas que se mostrarán en la tabla*/
        Object columnas[] = {"rolId", "funId", "rolNombre", "funNombre"};
        /*Es necesario añadir las columnas al modelo de la Tabla*/
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        /*Añadidas las columnas y el modelo se setea en la Tabla*/
        jTableRolFunc.setModel(modelo);
        for (RolFuncionalidad objRolFunc : lstRolFuncionalidad) {
            String idRol = String.valueOf(objRolFunc.getIdRol());
            String idFun = String.valueOf(objRolFunc.getIdFuncionalidad());
            String rolNombre = objRolFunc.getRolNombre();
            String funNombre = objRolFunc.getFunNombre();
            String modeloTemp[] = {idRol, idFun, rolNombre, funNombre};
            modelo.addRow(modeloTemp);
        }
        this.pack();            
        } catch (SQLException ex) {
            Logger.getLogger(IFRolUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRol = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaFuncionalidad = new javax.swing.JList();
        btnAñadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableRolFunc = new javax.swing.JTable();
        btnDesasignar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Asignar Rol a Funcionalidad");

        jLabel2.setText("Lista de Roles");

        jLabel3.setText("Lista de Funcionalidades");

        listaRol.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaRol);

        listaFuncionalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaFuncionalidadMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaFuncionalidad);

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jTableRolFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableRolFunc);

        btnDesasignar.setText("Desasignar");
        btnDesasignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesasignarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Lista de Roles y Funcionalidades");

        btnListar.setText("Listar Todos Rol/Funcionalidad");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDesasignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListar)
                        .addGap(4, 4, 4)
                        .addComponent(btnDesasignar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRolMouseClicked
        //indice seleccionado
        int[] selectedIx = this.listaRol.getSelectedIndices();  
        for (int i = 0; i < selectedIx.length; i++) {
            rol = (Rol) listaRol.getModel().getElementAt(selectedIx[i]);
            System.out.println(rol.getIdRol());
            System.out.println(rol.getRolNombre());
        }
    }//GEN-LAST:event_listaRolMouseClicked

    private void listaFuncionalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaFuncionalidadMouseClicked
        //indice seleccionado
        int[] selectedIx = this.listaFuncionalidad.getSelectedIndices();  
        for (int i = 0; i < selectedIx.length; i++) {
            func = (Funcionalidad) listaFuncionalidad.getModel().getElementAt(selectedIx[i]);
            System.out.println(func.getIdFuncionalidad());
            System.out.println(func.getFunNombre());
        }
    }//GEN-LAST:event_listaFuncionalidadMouseClicked

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        /* Para añadir funcionalidades a un rol
        Aqui hay que hacer un cambio para que varias funcionalidades puedan añadirse a un Rol*/
        int[] intcuentaroles= listaRol.getSelectedIndices();
        int[] intcuentafuncionalidad= listaFuncionalidad.getSelectedIndices();
        if (intcuentaroles.length>0 && intcuentafuncionalidad.length>0){
            int intidRol = rol.getIdRol();
            int intIdFunc = func.getIdFuncionalidad();
            boolean retorno = objManejadorRolFuncionalidad.RegistrarRolFuncionalidad(intidRol, intIdFunc);
            if (retorno==true){
                JOptionPane.showMessageDialog(this, "Funcionalidades asignadas con exito");
                ListarRolFuncionalidad();
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al registrar Rol/Funcionalidades");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un Rol y una o varias Funcionalidades");
        }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ListarRolFuncionalidad();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        listaRol.clearSelection();
        listaFuncionalidad.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDesasignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesasignarActionPerformed
        // nada por aca
          //Recupera la seleccion de filas y Columnas
        int row = (int) jTableRolFunc.getSelectedRow();
        //Obtiene el valor de la seleccion
        String IdRol = (String) jTableRolFunc.getModel().getValueAt(row, 0);
        String IdFun = (String) jTableRolFunc.getModel().getValueAt(row, 1);
        boolean resultado = objManejadorRolFuncionalidad.DesasignarRolFuncionalidad(Integer.parseInt(IdRol), Integer.parseInt(IdFun));
        if (resultado==true){
            JOptionPane.showMessageDialog(this, "Rol/Funcionalidad Desasignado con exito");
            ListarRolFuncionalidad();
        }
        else{
            JOptionPane.showMessageDialog(this, "Error al desasignar Rol/Funcionalidad");
        }
    }//GEN-LAST:event_btnDesasignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDesasignar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableRolFunc;
    private javax.swing.JList listaFuncionalidad;
    private javax.swing.JList listaRol;
    // End of variables declaration//GEN-END:variables
}
