/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BusinessLogic.BLRol;
import BusinessLogic.BLRolUsuario;
import BusinessLogic.BLUsuario;
import Clases.Rol;
import Clases.RolUsuario;
import Clases.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daguaman
 */
public class IFRolUsuario extends javax.swing.JInternalFrame {
    BusinessLogic.BLRol objManejadorRoles = new BLRol();
    BusinessLogic.BLUsuario objManejadorUsuario = new BLUsuario();
    BusinessLogic.BLRolUsuario objManejadorRolUsuario = new BLRolUsuario();
    Usuario usu =null;
    Rol rol =null;

    /**
     * Creates new form IFRolUsuario
     */
    public IFRolUsuario() throws SQLException {
        initComponents();
        CargarRoles();
        CargarUsuarios();
        ListarRolUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRoles = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableRolUsuario = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnListarRolUsuario = new javax.swing.JButton();
        btnDesasignar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Asignar Roles a Usuario");

        listaRoles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRolesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaRoles);

        listaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaUsuarios);

        jLabel2.setText("Lista de Usuarios");

        jLabel3.setText("Lista de Roles");

        jTableRolUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableRolUsuario);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Roles y Usuarios");

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnListarRolUsuario.setText("Listar Roles/Usuarios");
        btnListarRolUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRolUsuarioActionPerformed(evt);
            }
        });

        btnDesasignar.setText("Desasignar Rol/Usuario");
        btnDesasignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesasignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnListarRolUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDesasignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnListarRolUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesasignar)))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaRolesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRolesMouseClicked
        
        //indice seleccionado
        int[] selectedIx = this.listaRoles.getSelectedIndices();  
        for (int i = 0; i < selectedIx.length; i++) {
            rol = (Rol) listaRoles.getModel().getElementAt(selectedIx[i]);
            System.out.println(rol.getIdRol());
            System.out.println(rol.getRolNombre());
        }
    }//GEN-LAST:event_listaRolesMouseClicked

    private void listaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaUsuariosMouseClicked
        
        //indice seleccionado
        int[] selectedIx = this.listaUsuarios.getSelectedIndices();  
        for (int i = 0; i < selectedIx.length; i++) {
            usu = (Usuario) listaUsuarios.getModel().getElementAt(selectedIx[i]);
            System.out.println(usu.getIdUsuario());
            System.out.println(usu.getUsNombres());
        }
    }//GEN-LAST:event_listaUsuariosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        listaRoles.clearSelection();
        listaUsuarios.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Para añadir roles a un usuario
        int[] intcuentaroles= listaRoles.getSelectedIndices();
        int[] intcuentausuarios= listaUsuarios.getSelectedIndices();
        if (intcuentaroles.length>0 && intcuentausuarios.length>0){
            int intidRol = rol.getIdRol();
            int intIdUsuario = usu.getIdUsuario();
            boolean retorno = objManejadorRolUsuario.RegistrarRolUsuario(intidRol, intIdUsuario);
            if (retorno==true){
                JOptionPane.showMessageDialog(this, "Rol Asignado con exito");
                ListarRolUsuario();
            }
            else{
                JOptionPane.showMessageDialog(this, "Error al registrar Rol/Usuario");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un Rol y un Usuario");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnListarRolUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRolUsuarioActionPerformed
        ListarRolUsuario();
    }//GEN-LAST:event_btnListarRolUsuarioActionPerformed

    private void btnDesasignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesasignarActionPerformed
        //Recupera la seleccion de filas y Columnas
        int row = (int) jTableRolUsuario.getSelectedRow();
        //Obtiene el valor de la seleccion
        String IdRol = (String) jTableRolUsuario.getModel().getValueAt(row, 0);
        String IdUsu = (String) jTableRolUsuario.getModel().getValueAt(row, 1);
        boolean resultado = objManejadorRolUsuario.DesasignarRolUsuario(Integer.parseInt(IdRol), Integer.parseInt(IdUsu));
        if (resultado==true){
            JOptionPane.showMessageDialog(this, "Rol/Usuario Desasignado con exito");
            ListarRolUsuario();
        }
        else{
            JOptionPane.showMessageDialog(this, "Error al desasignar Rol/Usuario");
        }
    }//GEN-LAST:event_btnDesasignarActionPerformed
    public void CargarRoles() throws SQLException{
        DefaultListModel<Rol> dlm = new DefaultListModel<>();
        ArrayList<Rol> lstRol = objManejadorRoles.BuscarRol();
        Rol objRol = null;
        for (Rol lstRol1 : lstRol) {
            objRol = new Rol(lstRol1.getIdRol(), lstRol1.getRolNombre());
            dlm.addElement(objRol);
        }
        listaRoles.setModel(dlm);
    }
    
    public void CargarUsuarios() throws SQLException{
        DefaultListModel<Usuario> dlm = new DefaultListModel<>();
        ArrayList<Usuario> lstUsuario = objManejadorUsuario.Buscar("-1");
        Usuario objUsuario = null;
        for (Usuario lstUsuario1 : lstUsuario) {
            objUsuario = new Usuario(lstUsuario1.getIdUsuario(), lstUsuario1.getUsNombres());
            dlm.addElement(objUsuario);
        }
       // listaUsuarios.setModel(dlm);
       listaUsuarios.setModel(dlm);
    }
    
    public void ListarRolUsuario(){
    try {
        ArrayList<RolUsuario> lstRolUsuario =  objManejadorRolUsuario.BuscarRolUsuario();
        /*Es necesario crear un objeto con las columnas que se mostrarán en la tabla*/
        Object columnas[] = {"rolId", "usId", "rolNombre", "usNombres"};
        /*Es necesario añadir las columnas al modelo de la Tabla*/
        DefaultTableModel modelo = new DefaultTableModel(null, columnas);
        /*Añadidas las columnas y el modelo se setea en la Tabla*/
        jTableRolUsuario.setModel(modelo);
        for (RolUsuario objRolUsuario : lstRolUsuario) {
            String idRol = String.valueOf(objRolUsuario.getIdRol());
            String idUs = String.valueOf(objRolUsuario.getIdUsuario());
            String rolNombre = objRolUsuario.getRolNombre();
            String usNombre = objRolUsuario.getUsNombres();
            String modeloTemp[] = {idRol, idUs, rolNombre, usNombre};
            modelo.addRow(modeloTemp);
        }
        this.pack();            
        } catch (SQLException ex) {
            Logger.getLogger(IFRolUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesasignar;
    private javax.swing.JButton btnListarRolUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableRolUsuario;
    private javax.swing.JList listaRoles;
    private javax.swing.JList listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
