/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUISimulaSistema;

import BusinessLogic.BLFuncionalidad;
import BusinessLogic.BLModFuncionalidad;
import BusinessLogic.BLRolFuncionalidad;
import Clases.Funcionalidad;
import Clases.ModFuncionalidad;
import Clases.RolFuncionalidad;
import java.util.ArrayList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author daguaman
 */
public class JFrameContable extends javax.swing.JFrame {
    BusinessLogic.BLFuncionalidad objManejadorFuncionalidad = new BLFuncionalidad();
BusinessLogic.BLRolFuncionalidad objManejaRolFun = new BLRolFuncionalidad();
BusinessLogic.BLModFuncionalidad objManejadorModFun = new BLModFuncionalidad();
dameAcceso da = new dameAcceso();
JMenu menu1;
    /**
     * Creates new form JFrameContable
     * 
     */
    IFAccesos objAcceso = null;
    public JFrameContable() {
        initComponents();
        //Llamada al Método Liberar
        Liberar();
        //Llamada al método para habilitar o deshabilitar menus dependiendo del Rol
      //  HabilitaMenus();
        //Llamada al método para habilitar o deshabilitar menuItems dependiendo del Rol
      //  HabilitaMenuItems();
        /*Comprueba que el objeto creado para manipular el Internal Frame sea vacio,
        de lo contrario creará muchas veces un internal framw así se haya creado uno
        con esto controlamos que solo se cree una vez y sobre ese operar*/
        if (objAcceso==null){
            //Crea el objeto para manipular el Internal Frame
            objAcceso = new IFAccesos();
            objAcceso.setVisible(true);
            jDesktopPane1.add(objAcceso);
            
        }
       // CargarFuncionalidad(3);
      // CargarFuncionalidad(objAcceso.RolUs);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        bMenus = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 995, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        jMenu9.setText("Acceder");
        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu9MouseClicked(evt);
            }
        });
        bMenus.add(jMenu9);

        setJMenuBar(bMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MouseClicked
        // TODO add your handling code here:
        //CargarFuncionalidad(4);
        
    }//GEN-LAST:event_jMenu9MouseClicked

    public void Liberar(){
        if (objAcceso!=null){
            objAcceso.dispose();
            objAcceso = null;
        }
        
    }
    
   
    
   
     public  void CargarFuncionalidad(int rol){
        try{
            System.out.println("CargarFUncionalidad");
            /*Añade al módulo denominado JMenu9
            funcionalidades que serán los JMenuItems de dicho Menú que sería el Módulo
            Por el momento se ha habilitado el JMenu9 y las Funcionalidades de dicho Menu
            */
           // ArrayList<Funcionalidad> lstFuncionalidad = objManejadorFuncionalidad.Buscar("-1");
            ArrayList<RolFuncionalidad> rlFuncionalidad = objManejaRolFun.BuscarPorRol(rol);
            for (RolFuncionalidad lstFuncionalidad1 : rlFuncionalidad) {
              //  menu1.add(lstFuncionalidad1.getFunNombre());
              menu1 = new JMenu(lstFuncionalidad1.getFunNombre()+"");
              int idFuncion = lstFuncionalidad1.getIdFuncionalidad();
            ArrayList<ModFuncionalidad> lstModFun = objManejadorModFun.BuscarModFuncionID(idFuncion);
                for(ModFuncionalidad lstmfun: lstModFun){
                    menu1.add(lstmfun.getModNombre());
                }
                
              bMenus.add(menu1);
              //this.repaint();
            }
        }
        catch(Exception ex){
            String msn = ex.getMessage();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameContable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bMenus;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    // End of variables declaration//GEN-END:variables
}
